version: '3.1'

services:

    openkm:
        image: openkm/openkm-ce:latest
        environment:
            - "JAVA_OPTS=-Djdbc.url=jdbc:postgresql://openkm_db:5432/openkm"
        ports:
            - 8080:8080
            - 2002:2002
        depends_on:
            - openkm_db
    openkm_db:
        image: postgres:latest
        volumes:
            - openkm_vol:/var/lib/postgresql/data/pgdata
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=openkm
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5433:5432            

volumes:
    openkm_vol: {}
        